stages:
  - ci
  - cd

before_script:
  - nvm install
  - nvm use
  # - echo "unsafe-perm = true" >> ~/.npmrc
  - npm install pnpm -g
  - npm install yarn -g

check:
  stage: ci
  tags:
    - fe
    - xdev
  only:
    - branches
  except:
    - master
    - developer
    - release
  script:
    - yarn setup
